# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_rustyglm_wrappers", use_symbols = TRUE, package_name = "rustyglm")

#' @usage NULL
#' @useDynLib rustyglm, .registration = TRUE
NULL

#' Ajusta un GLM Poisson desde R.
#'
#' @param response Vector numérico de la variable respuesta.
#' @param x_flat   Matriz de diseño como vector en orden column-major (como R la guarda).
#' @param nrows    Número de filas (observaciones).
#' @param ncols    Número de columnas (variables + intercepto).
#'
#' @return Vector numérico con los coeficientes estimados.
#' @export
glm_fit_poisson <- function(response, x_flat, nrows, ncols) .Call(wrap__glm_fit_poisson, response, x_flat, nrows, ncols)


# nolint end
