# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_rustyglm_wrappers", use_symbols = TRUE, package_name = "rustyglm")

#' @usage NULL
#' @useDynLib rustyglm, .registration = TRUE
NULL

#' Ajusta un GLM desde R usando RustyStats core.
#' @export
glm_fit_rust <- function(response, x_flat, nrows, ncols, family, offset, reg_type, lambda, l1_ratio) .Call(wrap__glm_fit_rust, response, x_flat, nrows, ncols, family, offset, reg_type, lambda, l1_ratio)

#' Ajusta un GLM con penalizaciones multi-tipo (SMuRF — FISTA Rust).
#' @export
smurf_fit_rust <- function(response, x_flat, nrows, ncols, family, offset, weights, pen_types, col_starts, col_ends, pen_mats_flat, pen_mat_nrows, pen_mat_ncols, q_mats_flat, q_mat_nrows, q_mat_ncols, eigvals_flat, eigval_lens, lambda1_flat, lambda1_lens, lambda2s, group_ids, lambda, maxiter, epsilon, step_init, tau, start) .Call(wrap__smurf_fit_rust, response, x_flat, nrows, ncols, family, offset, weights, pen_types, col_starts, col_ends, pen_mats_flat, pen_mat_nrows, pen_mat_ncols, q_mats_flat, q_mat_nrows, q_mat_ncols, eigvals_flat, eigval_lens, lambda1_flat, lambda1_lens, lambda2s, group_ids, lambda, maxiter, epsilon, step_init, tau, start)


# nolint end
